---
- name: Create pecl extension files (cli)
  file:
    path: "/etc/php/7.3/cli/conf.d/40-{{ item }}.ini"
    state: touch
  with_items: "{{ pecl_extensions_cli }}"

- name: Add pecl extensions (cli)
  lineinfile:
    path: "/etc/php/7.3/cli/conf.d/40-{{ item }}.ini"
    regexp: '^extension=/usr/lib/php/20180731/{{ item }}'
    line: 'extension=/usr/lib/php/20180731/{{ item }}.so'
  with_items: "{{ pecl_extensions_cli }}"
  notify: restart php

- name: Remove pecl extension files (cli)
  file:
    path: "/etc/php/7.3/cli/conf.d/40-{{ item }}.ini"
    state: absent
  with_items: "{{ remove_pecl_extensions_cli }}"
  notify: restart php
