---
- hosts: server
  become: yes
  vars:
    basic_packages:
      - vim
      - curl
      - git
  tasks:
    - name: Install basics
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ basic_packages }}"
