---
- hosts: server
  become: yes
  vars:
    php_extensions:
      - libpq-dev
      - zlib1g-dev
      - libicu-dev
      - g++
      - libgmp-dev
      - libmcrypt-dev
      - libbz2-dev
      - libpng-dev
      - libfreetype6-dev
      - libfontconfig
      - libzip-dev
      - libxml2-dev
      - php7.3-bcmath
      - php7.3-curl
      - php7.3-gd
      - php7.3-gmp
      - php7.3-intl
      - php7.3-json
      - php7.3-soap
      - php7.3-mbstring
      - php7.3-pgsql
      - php7.3-zip
      - php7.3-bz2
      - php7.3-pdo
      - php7.3-readline
      - composer
    pecl_packages:
      - redis-5.0.2
      - mcrypt-1.0.2
    pecl_extensions_cli:
      - redis
      - mcrypt
    pecl_extensions_fpm: "{{ pecl_extensions_cli }}"
  roles:
    - php73
